#!/bin/bash

set -e

folder_name=''
language='cpp'

if [ -z "$1" ]; then
      echo "No day number specified."
      echo "Usage: ./new <day-number> - e.g. ./new 17"
      exit 1
fi

if [ -z "$2" ]; then
      echo "No language specified, defaulting to ${language}."
else
      language="$2"
fi

printf -v folder_name "day%02d" $1

# this will fail if there is already a folder with that name, which is probably good
mkdir "${folder_name}"

cp "./_skeleton.${language}" "./${folder_name}/part1.${language}"
echo "Created ./${folder_name}/part1.${language}"
cp "./_skeleton.${language}" "./${folder_name}/part2.${language}"
echo "Created ./${folder_name}/part2.${language}"
touch "./${folder_name}/sample.txt"
echo "Created ./${folder_name}/sample.txt"
touch "./${folder_name}/input.txt"
echo "Created ./${folder_name}/input.txt"
